config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :food_donations do
      member do
        get :request_donation
        get :cancel
        get :complete
      end
    end

    resource :profile, only: [:edit, :update]
  end
  devise_scope :user do
    # to resolve devise conflicting behavior
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: redirect('/users/password/new')
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'welcome/index'
  root 'welcome#index'
end

app/models/food_donation.rb
class FoodDonation < ApplicationRecord
  belongs_to :user, foreign_key: 'restaurant_id'

  validates :available_at, presence: true
  validates :quantity, presence: true
  validates :note, presence: true

  enum status: {
    available: 0,
    requested: 1,
    picked_up: 2
  }

  def self.to_csv
    attributes = %w[restaurant charity quantity status note review available_at created_at updated_at]

    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |donation|
        csv << attributes.map { |attr| donation.send(attr) }
      end
    end
  end

  def charity
    User.find_by(id: charity_id)&.profile&.name
  end

  def restaurant
    self.user.profile.name
  end

  def profile
    self.user.profile
  end
end

app/controllers/food_donations_controller.rb
class FoodDonationsController < ApplicationController
  before_action :set_food_donation, only: %i[show edit update destroy request_donation cancel complete]
  before_action :ensure_user_is_restaurant, only: %i[new create edit update destroy]
  before_action :ensure_user_is_charity, only: %i[request_donation cancel complete]

  # GET /food_donations
  # GET /food_donations.json
  def index
    if current_user.charity?
      requested_donation = FoodDonation.where(charity_id: current_user.id, status: 1)
      @food_donations = requested_donation.empty? ? FoodDonation.all.available : requested_donation
    elsif current_user.restaurant?
      @food_donations = current_user.food_donations.all
    end
    respond_to do |format|
      format.html
      format.csv { send_data @food_donations.to_csv, filename: "donations-#{Date.today}.csv" }
    end
  end

  # GET /food_donations/1
  # GET /food_donations/1.json
  def show; end

  # GET /food_donations/new
  def new
    @food_donation = current_user.food_donations.build
  end

  # GET /food_donations/1/edit
  def edit; end

  # POST /food_donations
  # POST /food_donations.json
  def create
    @food_donation = current_user.food_donations.new(food_donation_params)
    # set donation's status to available
    @food_donation.status = 0
    respond_to do |format|
      if @food_donation.save
        format.html { redirect_to food_donations_path, notice: 'Food donation was successfully created.'}
        format.json { render :show, status: :created, location: @food_donation }
      else
        format.html { render :new }
        format.json { render json: @food_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_donations/1
  # PATCH/PUT /food_donations/1.json
  def update
    respond_to do |format|
      if @food_donation.update(food_donation_params)
        format.html { redirect_to @food_donation, notice: 'Food donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_donation }
      else
        format.html { render :edit }
        format.json { render json: @food_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_donations/1
  # DELETE /food_donations/1.json
  def destroy
    @food_donation.destroy
    respond_to do |format|
      format.html { redirect_to food_donations_url, notice: 'Food donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def request_donation
    @food_donation.charity_id = current_user.id
    @food_donation.status = 1
    @food_donation.save
    ApplicationMailer.request_confirm(@food_donation).deliver
    redirect_to food_donations_path, notice: 'You have requested this food donation successfully.'
  end

  def cancel
    @food_donation.charity_id = nil
    @food_donation.status = 0
    @food_donation.save
    redirect_to food_donations_path, notice: 'The request was cancelled.'
  end

  def complete
    @food_donation.status = 2
    @food_donation.save
    redirect_to food_donations_path, notice: 'The food was picked up.'
  end


  protected

  def ensure_user_is_restaurant
    redirect_to(root_path) unless current_user.restaurant?
  end

  def ensure_user_is_charity
    redirect_to(root_path) unless current_user.charity?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food_donation
    @food_donation = FoodDonation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def food_donation_params
    params.fetch(:food_donation, {}).permit(:note, :available_at, :quantity)
  end
end

app/helpers/food_donations_helper.rb
module FoodDonationsHelper
end

app/views/food_donations/_form.html.erb
<div class="form">
  <%= form_with(model: food_donation, local: true) do |form| %>
  <% if food_donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_donation.errors.count, "error") %>
        prohibited this food_donation from being saved:</h2>
      <ul>
        <% food_donation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label 'How many people it can serve?'%>
    <%= form.number_field :quantity, required: true, class: "form-control", placeholder: "10, 15..." %>
  </div>
  <div class="form-group">
    <%= form.label 'When it would be available?' %>
    <%= form.text_field :available_at, required: true, class: "form-control", id: "datetimepicker" %>
  </div>
  <div class="form-group">
    <%= form.label 'Leave a note for the charity' %>
    <%= form.text_field :note, required: true, class: "form-control", placeholder: "food allergies, veggie-friendly..." %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn-primary" %>
  </div>
<% end %>
</div>

<script type="text/javascript">
$(document).ready(function () {
  var $j = jQuery.noConflict();
  $j('#datetimepicker').datetimepicker({step: 15, minDate: 0, maxDate: '+1970/01/02'});
});
</script>

app/views/food_donations/edit.html.erb
<body id="food_donation">
  <section class="portfolio">
    <div class="container">
      <h1>Editing Food Donation</h1>
      <p id="notice"><%= notice %></p>
      <%= render 'form', food_donation: @food_donation %>

      <%= link_to 'Back', food_donations_path %>
    </div>
  </section>
</body>

app/views/food_donations/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDqYN_EO5bhjPwWi7zNzsbXUhrQsaaMSTM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>

<body id="food_donation">
  <section class="portfolio">
    <div class="container">
      <div class="card">
        <div class="card-header">
          Food Donations
          <%= current_user.restaurant? ? '(Restaurant)' : '(Charity)' %>
        </div>
        <div class="card-body">
          <p id="notice"><%= notice %></p>
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th colspan="1">ID</th>
                <th colspan="1">Quantity</th>
                <% if current_user.restaurant? %>
                  <th colspan="1">
                    Status
                  </th>
                <%end%>
                <% if current_user.charity? %>
                  <th colspan="1">Detail
                  </th>
                <% end%>
                <th colspan="2">Available</th>
                <th colspan="5">Note</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              <% @food_donations.each do |food_donation| %>
                <tr>
                  <td colspan="1">
                    <%= food_donation.id %>
                  </td>
                  <td colspan="1">
                    <%= food_donation.quantity %>
                  </td>
                  <% if current_user.restaurant? %>
                    <td colspan="1">
                      <%= food_donation.status %>
                    </td>
                  <%end%>
                  <% if current_user.charity? %>
                    <td colspan="1">
                      <a data-toggle="modal" data-target="#myModal<%=food_donation.id%>" data-lat="<%=food_donation.profile.lat%>" data-id="<%=food_donation.id%>" data-lng="<%=food_donation.profile.lon%>" href="">Restaurant Info</a>
                    </td>
                    <div id="myModal<%=food_donation.id%>" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <div class="modal-body">
                            <div class="row">
                              Name:
                              <%= food_donation.profile.name %>
                            </div>
                            <div class="row">
                              Address Line 1:
                              <%= food_donation.profile.addr_line_1 %>
                            </div>
                            <div class="row">
                              Address Line 2:
                              <%= food_donation.profile.addr_line_2 %>
                            </div>
                            <div class="row">
                              City:
                              <%= food_donation.profile.city %>
                            </div>
                            <div class="row">
                              State:
                              <%= food_donation.profile.state %>
                            </div>
                            <div class="row">
                              Zip:
                              <%= food_donation.profile.zip %>
                            </div>
                            <div class="row">
                              Phone:
                              <%= food_donation.profile.phone_number %>
                            </div>
                            <div class="row">
                              Map:
                            </div>
                            <div style='width: 100%'>
                              <div id="map_canvas<%=food_donation.id%>" style="width: 'auto'; height: 250px;"></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end%>
                  <td colspan="2">
                    <%= food_donation.available_at %>
                  </td>
                  <td colspan="5">
                    <%= food_donation.note %>
                  </td>
                  <td>
                    <% if current_user.restaurant? %>
                      <% if food_donation.available? %>
                        <li><%= link_to 'Edit', edit_food_donation_path(food_donation) %></li>
                        <li><%= link_to 'Cancel', food_donation, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                      <% end %>
                      <% elsif current_user.charity? %>
                        <% if food_donation.available? %>
                          <li><%= link_to 'Request', request_donation_food_donation_path(food_donation) %></li>
                        <% else %>
                          <li>
                            <%= link_to 'Complete', complete_food_donation_path(food_donation) %>
                          </li>
                          <li>
                            <%= link_to 'Cancel', cancel_food_donation_path(food_donation)%>
                          </li>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <% if current_user.restaurant? %>
              <div class='row'>
                <ul>
                  <li>
                    <%= link_to 'New Food Donation', new_food_donation_path %>
                  </li>
                  <li>
                    <%= link_to 'Export Donation History', food_donations_path(format: :csv) %>
                  </li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </body>

app/views/food_donations/new.html.erb
<body id="food_donation">
  <section class="portfolio">

    <div class="container">
      <div class="card">
        <div class="card-header">
          Create A New Food Donation
        </div>
        <div class="card-body">
          <%= render 'form', food_donation: @food_donation %>

          <%= link_to 'Back', food_donations_path %>
        </div>
      </div>
    </div>
  </section>
</body>