config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    resources :food_donations do
      member do
        get :request_donation
        get :cancel
        get :complete
      end
    end

    resource :profile, only: [:edit, :update]
  end
  devise_scope :user do
    # to resolve devise conflicting behavior
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: redirect('/users/password/new')
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'welcome/index'
  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Location</h4>
        <p class="lead mb-0">25 Park Place
          <br>Atlanta, GA, 30303</p>
      </div>
      <div class="col-md-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Around the Web</h4>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-fw fa-facebook-f"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-fw fa-google-plus-g"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
              <i class="fab fa-fw fa-twitter"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4 class="text-uppercase mb-4">About Us</h4>
        <p class="lead mb-0">
          <p>
            Aleck Palad
          </p>
          <p>
            Leticia Garcia Sainz
          </p>
          <p>
            Naymish Vaghela
          </p>
          <p>
            Kainan Zhang
          </p>
      </ul>
    </div>
  </div>
</div>
</footer>

<div class="copyright py-4 text-center text-white">
<div class="container">
  <small>Copyright &copy; FoodLink 2019</small>
</div>
</div>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-to-top d-lg-none position-fixed ">
<a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
  <i class="fa fa-chevron-up"></i>
</a>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/">Food Link</a>
      <button
        class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded"
        type="button"
        data-toggle="collapse"
        data-target="#navbarResponsive"
        aria-controls="navbarResponsive"
        aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item mx-0 mx-lg-1 dropdown">
              <a class="nav-link dropdown-toggle py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hi, <%=current_user.profile.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/edit">Account</a>
                <a class="dropdown-item" href="/profile/edit">Profile</a>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to "Food Donations", food_donations_path, method: :get, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
              </li>
            <% else %>
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/users/sign_up">Sign Up</a>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/users/sign_in">Log in</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodLink</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  </head>

  <body style="padding-top: 30px;">
    <%= render :partial => "layouts/header" %>
    <%= yield %>
    <%= render :partial => "layouts/footer" %>
  </body>
</html>